[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "megalodon"
readme = "README.md"
description = "Megalodon: Applications of Modular Co-Design for De Novo 3D Molecule Generation"
authors = [{ name = "NVIDIA", email = "bionemofeedback@nvidia.com" }]
requires-python = ">=3.10"
license = { file = "LICENSE/license_code.txt" }
dynamic = ["version"]
dependencies = [
    # external
    'torch==2.12.0',
    'torch_geometric==2.8.0',
    'torch-sparse==0.6.18',
    'torch-scatter==2.1.2',
    'hydra-core==1.3.2',
    'omegaconf==2.3.0',
    'rdkit==2026.3.3',
    'lightning==2.6.5',
    'einops==0.8.2',
    'wandb==0.27.2',
    'zarr==2.18.3',
    'numcodecs==0.13.1',
    'h5py==3.12.1',
    'pandas==2.3.3',
]


[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
namespaces = true


[tool.setuptools.dynamic]
version = { file = "VERSION" }
